### ISSUE TITLE
ISP DNS Leaking  in Passwall And SSR Plus with DNS Not Working HOW To Fix ?

### ISSUE THREAD

**Issue by sachin-senal** [jiajiaxd/openwrt_x86#2]
Hello 

Im using my private vpn connection its trojan . also using my main connection to TLS all working fine but my ISP dns is leaking google dns not using only appear ISP dns server this is happening in passwall and SSR plus dns is not working How i can fix this please help me 😊and ios notifications not working both passwall and ssr plus services 😊

thank you

**Comment by jiajiaxd** [comment]
you can disable dns split-flow by making settings below.
![image](https://user-images.githubusercontent.com/51043917/165102059-9f0ef9a4-6ccc-42d6-b18e-6bc7113b0db0.png)
i strongly propose using adguardhome to replace dnsmasq(you can do it by replacing local 53 port)

**Comment by jiajiaxd** [comment]
long time no respond;closed.
