### ISSUE TITLE
About Youtube

### ISSUE THREAD

**Issue by sachin-senal** [jiajiaxd/openwrt_x86#3]
Hello i cant comment in youtube its say "failed to post comment " how i can fix this ?

**Comment by jiajiaxd** [comment]
after testing,I don't have such a problem.which plugin are you  using(passwall/helloworld)?

**Comment by sachin-senal** [comment]
Thank you for reply
![image](https://user-images.githubusercontent.com/101747459/165187565-7b09599d-dad2-469d-a6c9-885b41d0cb45.png)


I'm using passwall  like this error giving  im using private vps server and shadowrocket ios app working fine but openwrt giving this error 

thank you

**Comment by jiajiaxd** [comment]
you should turn to [repository:passwall](https://github.com/xiaorouji/openwrt-passwall)
