### ISSUE TITLE
XBOX LIVE PACKET LOSS

### ISSUE THREAD

**Issue by sachin-senal** [jiajiaxd/openwrt_x86#4]
**Hello After use OpenWrt  My xbox packet is loss 100% how i can fix this** 

![image](https://user-images.githubusercontent.com/101747459/165209729-0370f435-b68b-40f7-b9f5-452d665acdae.png)

**Comment by jiajiaxd** [comment]
i don't have xbox devices,so i can't fix this issue.

**Comment by sachin-senal** [comment]
> i don't have xbox devices,so i can't fix this issue.

No  its windows
