### ISSUE TITLE
分区有问题

### ISSUE THREAD

**Issue by xaisc** [jiajiaxd/openwrt_x86#5]
固件里的分区和权限有问题，写盘或者用虚机进去之后空间只有几兆，没法升级或者安装插件。ps：昆山论坛注册还要收钱，好在github是免费注册。

**Comment by jiajiaxd** [comment]
因为每个人的使用情况不同，无法定出一个合适的预定空间，所以请自行扩容
参考教程:https://www.openwrt.pro/post-594.html

顺便一提，幸好你没在恩山发帖询问
因为我从来不看恩山的帖子😂
