### ISSUE TITLE
固件里的AdGuardHome有问题

### ISSUE THREAD

**Issue by xaisc** [jiajiaxd/openwrt_x86#6]
内部集成的AdGuardHome插件质量不高，奇葩的有两套配置，分别是AdGuardHome和全小写的adguardhome。导致开机初始化的时候一套配置，服务停止再重启后又是另一套配置，还互不同步。

**Comment by jiajiaxd** [comment]
请前往上游仓库反馈
https://github.com/rufengsuixing/luci-app-adguardhome

**Comment by jiajiaxd** [comment]
未来可能会考虑大佬的fork版本
https://github.com/kongfl888/luci-app-adguardhome

**Comment by xaisc** [comment]
你的固件运行效率很高，smartDNS配合AdGuardHome，简单组合一下就有平均11ms的处理时间。赞一个
